### ISSUE TITLE
Some feedback

### ISSUE THREAD

**Issue by MisterLight** [BabylonJS/Editor#115]
Hi, :) I just discovered the babylon editor and im playing with it, I had been working with Unity for 4 years and I feels that moving to this engine is very intuitive and easy. However I still miss some little things that, I think, will improve the usability and found some bugs on desktop version

- I thinks it would be cool to increase the size of transform axis ( when your are close to the object they are very small)

- In the inspector window, you can see the Scripts section, but when i attach a new script, only appear in Code Editor window, this is for me a bit confusing.

- When I create a new script and gave it a name (for example, "testScript") it would be cool the name of the script would be like the given name, not "Script"

- Sure the internal Code Editor its great when you use the online version of Babylon Editor, but on desktop I would like to click and open the code on a custom editor (VS Code, VS Community) etc

- I save my project, but when I click on the ".editorproject", do not open, its stuck on "Loading scene"

- In the animation window, there is option to view all the animation properties (rotation, position, scaling) together on the same timeline? Is a bit annoying when i need to coordinate the rotation with  a specific frame of the position.

- Maybe this subjective, but is a bit difficult for me to see properties values on the screen cause the color letter (for example: the light blue of position x, y z or the turquoise color of the object name)

Thank you so much for your effort, babylon.js is a great engine and with a great editor like this, i think we can make incredible things easier.

**Comment by julien-moreau** [comment]
Hey @MisterLight :)
Thanks a lot for these feedbacks! Always a pleasure to have feedbacks and improve the editor :)

 Here are my answers:
* I thinks it would be cool to increase the size of transform axis ( when your are close to the object they are very small) **DOING ASAP**

* When I create a new script and gave it a name (for example, "testScript") it would be cool the name of the script would be like the given name, not "Script" **DOING ASAP**

* Sure the internal Code Editor its great when you use the online version of Babylon Editor, but on desktop I would like to click and open the code on a custom editor (VS Code, VS Community) etc. Already working on it via a VSCode extension. I'm using a VSCode extension because I still keep the online version compatible with the electron version for the moment. VSCode has a bug with virtual file systems and typescript features. I asked for the status of the issue here: https://github.com/Microsoft/vscode/issues/59650 Can you upvote so it can be fixed earlier? Thanks!**

* I thinks it would be cool to increase the size of transform axis ( when your are close to the object they are very small) **DOING ASAP**

* In the inspector window, you can see the Scripts section, but when i attach a new script, only appear in Code Editor window, this is for me a bit confusing. **I have to documentate more this part and don't draw "Scripts" if no scripts available, DOING ASAP**

I save my project, but when I click on the ".editorproject", do not open, its stuck on "Loading scene" **I must improve this section: https://doc.babylonjs.com/resources/loading_saving have you saved your .editorproject in the same folder as your assets files? It is needed and I'm working on this to save wherever you want.**

In the animation window, there is option to view all the animation properties (rotation, position, scaling) together on the same timeline? Is a bit annoying when i need to coordinate the rotation with a specific frame of the position. **Adding for a future realease. This tool is missing a lot of things, zoom for example, and that kind of feature you asked. Will work on it once the 2.5.3 is released. That means ASAP :)**

**Comment by MisterLight** [comment]
Thank you so much Julien!

About the saving scene, I just install the desktop editor and save the default scene with "save project" creating the .editoeproject but no texture or material was generated.

**Comment by julien-moreau** [comment]
The philosophie of the editor tends to "don't do what you can do in Blender using the editor". Basically, the editor will never work with a standalone .editorproject file. It will always be linked to a scene file (typically a .babylon file) and save the deltas. You can see the editor as an added value to your scene.

The philosophie is also "do what you can't do in Blender" typically adding particle systems, sky effects, custom scripts, graphs, etc.

Blender is an example. 3d modelers have powerful tools even to create a simple cube that the editor will never have. So let's create geometries with blender or 3ds Max and just add values using the editor.

In you case, you should save the .editorproject near your scene file and textures (and sounds, etc.) so the paths will never be broken.

I fixed all the "DOING ASAP" points, I'm releasing asap for you :)

**Comment by MisterLight** [comment]
Thank you so much! I will look a this later when I have more time. 

Btw, yesterday I was creating simple scripts test to figure out what can I do with the editor and what can be improve.

A little thing that I note is that maybe a Destroy method on game object  life cycle could be useful for cleaning resources or trigger some event/notifications to other object 

what do you think?

**Comment by julien-moreau** [comment]
Excellent thanks!
I'll update the documentation of the editor, yesterday I re-worked the way to manage projects (instead of saving only the delta, i'll save morely like a Unity project.

Adding the issue for you feedback on scripts :)

**Comment by MisterLight** [comment]
Hey!! I come back, with more feedback and some doubts  :)

- Add transform arrows to other nodes like spot light, camera, sound etc., is a bit annoying when Im trying to move it.

- By default when you select a object, the transform arrow should be enable. I think its would be more intuitive than just looking at the selected node in the hierarchy.

- When I want to select more than 1 node, I click on the node and then I press shift + click on the final node , but, when the final node that I clicked is a child of another node, the selection dont work.

- Invert the color of the arrow icon that appear on the parent when you attach a cild (when you are using the light theme, the arrow is white, like the background color of the editor, so is a bit difficult to see it clearly)  I would change the color to black for light theme, and white for darker theme.

- Would be, in future, support for 2d sprites and orthographic camera?

- When I delete a camera from the hierarchy, I didnt find a way to create a new one. Not appear in the "Add" dropdown menu.

- Im a real noob with the editor,  right now im reading the docs, :) but I dont find a way to reference a gameobject of the hierarchy and the attached script os this one, in Unity i just drag and drop the target object inside the the representation of my script in the editor and use the "GetComponent<T>" method in my script to access the attached script or "component" of the target and his properties. How can do the same here?

**Comment by julien-moreau** [comment]
Hi @MisterLight !
I'm fixing these issues right now
