### ISSUE TITLE
Get error 'editorMetadatas' is missing in type 'Scene'

### ISSUE THREAD

**Issue by Giv0** [BabylonJS/Editor#151]
I'm trying to add in the camera class, but I get this error.  Here is the code that  gives it.

```
public static CreateCamera (editor: Editor): Camera {
        const camera =  new BABYLON.FreeCamera('New Camera', new BABYLON.Vector3(0, 0, 0), editor.core.scene, true);
        this.AddToGraph(editor, camera);

        return camera;
    }
```

**Comment by julien-moreau** [comment]
I cloned your repository and got an error:
src/editor/scene/scene-factory.ts:99:92 - error TS2345: Argument of type 'import("babylonjs/scene").Scene' is not assignable to parameter of type 'BABYLON.Scene'.
  Property 'editorMetadatas' is missing in type 'Scene'.

99         const camera =  new BABYLON.FreeCamera('New Camera', new BABYLON.Vector3(0, 0, 0), editor.core.scene, true);


This is due to the fact you are accessing BABYLON.FreeCamera instead of importing "FreeCamera" from babylonjs (on the top of the of the file).

Do the same for Vector3 and you'll be able to compile without any error :)
Can you confirm?

**Comment by Giv0** [comment]
I fixed it.  Gonna send a push request
