### ISSUE TITLE
"Watch Project Automatically" option inside preferences window does not work

### ISSUE THREAD

**Issue by MegsTan** [BabylonJS/Editor#196]
Sometimes the auto watch from the preference does not work, I usually use the terminal to watch for any changes using "npm run watch".

![AA](https://user-images.githubusercontent.com/44461836/88390643-406b3d80-cdeb-11ea-92e8-eb2b69e72fd7.png)

**Comment by julien-moreau** [comment]
Thanks for reporting! I'll let you know once fixed :)

**Comment by julien-moreau** [comment]
@MegsTan, beta.4 has been released! Can you confirm it fixes that bug on your side? Thanks :)
You can download the beta.4 here: https://github.com/BabylonJS/Editor/wiki/BabylonJS-Editor-v4.0.0-beta

**Comment by MegsTan** [comment]
Hi @julien-moreau ,

Thank you so much! I'm really happy we found BabylonJS Editor, I will check this out. Take care!

**Comment by MegsTan** [comment]
Hi @julien-moreau ,

I tried it several ways, still does not seem to work the assets and code are not being updated. I still had to go through terminal to do a manual watch. Not sure if I might be missing something.

**Comment by julien-moreau** [comment]
Hey @MegsTan !
I finally found a big bug and fixed it: the logs were the buggiest logs ever lol.

Unfortunately, except having node uninstalled I haven't reproduced your bug :(
If you type "CTRL+ALT+i" the devtools of the Editor will open (used to debug the Editor itself). When you activate the "Watch Project Automatically", can you share me the logs you can find with webpack in the devtool's console? That would help me a lot because I have found no way how to reproduce :(

**Comment by MegsTan** [comment]
Hi @julien-moreau  this bug seems to go away now in beta 6. Not sure if you were able to fix, I Will dig into it and see if it will come back. I'll close the ticket for now. Thank you! Stay safe!



Regards,

**Comment by julien-moreau** [comment]
Excellent! I think I found the bug as I said in my previous message. Hope it'll not come back! Ahah

Thanks again for reporting :)
