### ISSUE TITLE
Default branch should be 'develop'

### ISSUE THREAD

**Issue by MrMormon** [BabylonJS/Editor#2]
Master has no real readme or any code.

**Comment by julien-moreau** [comment]
Hi MrMormon :)

The Editor project is in its "stand by" mode due to the primary features I have to implement in the Babylon.js framework. I never forgot it and will certainly come back soon to provide a stable version. Unfortunately, the current version isn't enough to use.

Once I get a stable version, I'll update the master branch with the README

However, all contributions are welcome :)
