### ISSUE TITLE
Project From Windows Platform opened on Mac

### ISSUE THREAD

**Issue by MegsTan** [BabylonJS/Editor#205]
Hi @julien-moreau 

Hope you are having a great day! I would just like to know if this is MAC related or something else, We are sharing the project via a repository, however, after opening the project in the editor using a MAC we are getting a black scene with a bunch of errors. Can you direct us on something that we might be missing? Thanks in advance and keep safe.

![BabylonEditorMac](https://user-images.githubusercontent.com/44461836/88661160-a406ab00-d10a-11ea-9a7a-bd28928b61af.png)

![error](https://user-images.githubusercontent.com/44461836/88661170-aa952280-d10a-11ea-98e7-463d2fb83988.png)

**Comment by julien-moreau** [comment]
Hey @MegsTan ! I'm fine and hope you too!
According to the errors I see in the console, the error is more related to the Mac itself. I can see that you have a skinned mesh that has 273 bones (this is too much for sure and I'm too much a pure noob in 3d design to help you optimizing the skinned mesh) and at least too much for the video card of the Mac. I already experienced that kind of problem with my Mac :(

To validate that it is because of the skinned mesh(es), can you remove the skinned mesh from the scene, then save and then reload the project. If the same error still appears, try to remove all the skinned meshes and reload the project etc.

As you are using GIT, save your work before removing all skinned meshes, you'll be able revert these changes ^^

**Comment by MegsTan** [comment]
Hi @julien-moreau 

Thank you so much! I already informed the developer who works on Mac. In case we encounter an issue regarding this one. Wil try to reach back :) Please take care!!!
