### ISSUE TITLE
Exporting workflow doesn't works using desktop Windows app Editor 3.2.0 

### ISSUE THREAD

**Issue by Juanmaramon** [BabylonJS/Editor#212]
Hi, 

I'm following the basics editor workflow tutorial: https://doc.babylonjs.com/resources/explaining_workflow but when I'm trying to deploy it seems to be all correct:

`$ http-server -p 12338 -c-1 -v
Starting up http-server, serving ./
Available on:
  http://...:12338
  http://127.0.0.1:12338
Hit CTRL-C to stop the server
`
But trying to access on the web browser is not working with ERR_INVALID_REDIRECT error.

Can someone help?

Thanks!

**Comment by julien-moreau** [comment]
Hi @Juanmaramon thanks for reporting!

I think this is due to an "http-server" module bug on Window. Can you add "/index.html" in your URL? I think that will solve the problem (the error looks similar to this one: https://github.com/BabylonJS/Editor/issues/207)

Also, I recommand that you start using the V4 of the Editor instead of the V3 as the V4 has been made from scratch and is much more powerful/useful. It is also using latest @babylonjs modules with a better support.

Downloads of the V4 are available here: https://github.com/BabylonJS/Editor/wiki/BabylonJS-Editor-v4.0.0-beta
And the documentation still WIP for the V4: https://github.com/BabylonJS/Editor/blob/release/4.0.0/doc/00%20-%20welcome/doc.md

It would be useful that have you as a beta tester and share some feedbacks you may have using the V4 :)

Thanks again for reporting!

**Comment by Juanmaramon** [comment]
Thanks @julien-moreau! I will definitely try it out :)

Are there any forum to give feedback about V4? Also I have some questions about the scripting support.

Thank you

**Comment by julien-moreau** [comment]
Perfect! :)

Sure, you can post your bug reports or questions here: https://forum.babylonjs.com/
