### ISSUE TITLE
switching scene

### ISSUE THREAD

**Issue by undefinederror** [BabylonJS/Editor#244]
Using editor v4, linux, electron build

I create a new scene. File => New Project. This is created as `scene1`.
I run it in any of the 3 Browsers, I always only see `scene`, not the newly created scene

**Comment by julien-moreau** [comment]
Hey @undefinederror, this is the expected behavior at the moment as the Editor doesn't yet supports the option "Scene to start". If you look at the code in src/index.ts of your game, it loads the scene located at "./scenes/scene/scene.babylon". You'll have to manually choose what scene you would like to start here

**Comment by undefinederror** [comment]
gotcha, thank you!
![image](https://user-images.githubusercontent.com/8209966/103663824-d5b15700-4f71-11eb-8152-17b355581f7c.png)
