### ISSUE TITLE
Error when run the app

### ISSUE THREAD

**Issue by marcobertagna** [BabylonJS/Editor#307]
Hi,
we've tried to build and play the package, and we receive this error:

Unable to load from ./scenes/scene/scene.babylon: importScene of scene.babylon from Babylon.JS Editor version: v4.0.2, exporter version: v4.2.0
BJS - [12:16:48]: Unable to find a plugin to load babylon files. Trying to use .babylon default plugin. To load from a specific filetype (eg. gltf) see: https://doc.babylonjs.com/how_to/load_from_any_file_type

Can you help us?

Thank you for your time

**Comment by julien-moreau** [comment]
Hi @marcobertagna !

That's weird! I'm checking if I can reproduce. Do you have more details on the error? Like if the request to the .babylon file has a 404 or whatever?
What you can verify also:
- Check that you correctly import "cannon.js" in your project (like it is by default in the index.html of the workspace)
- In case you don't use physics, try to disable it in the inspector by selecting the scene and retry the export

In case the problem comes from physics, this documentation should help: https://github.com/BabylonJS/Editor/blob/release/4.0.0/doc/05%20-%20using-physics/using-physics.md#choosing-physics-engine

**Comment by Moriyer** [comment]
> Hi @marcobertagna !
> 
> That's weird! I'm checking if I can reproduce. Do you have more details on the error? Like if the request to the .babylon file has a 404 or whatever?
> What you can verify also:
> 
> * Check that you correctly import "cannon.js" in your project (like it is by default in the index.html of the workspace)
> * In case you don't use physics, try to disable it in the inspector by selecting the scene and retry the export
> 
> In case the problem comes from physics, this documentation should help: https://github.com/BabylonJS/Editor/blob/release/4.0.0/doc/05%20-%20using-physics/using-physics.md#choosing-physics-engine

Hello I meet the same question, I edit in Babylon.js Editor. I create a dummy node and add a component to it
![image](https://user-images.githubusercontent.com/24497259/124548156-e9c20c80-de5f-11eb-8dec-b86ccf125e5f.png)
I add some code in onStart to load a gltf file
![image](https://user-images.githubusercontent.com/24497259/124548301-1d9d3200-de60-11eb-82bb-77ea4ef1f53c.png)
when I click "Play", SceneLoader work correctly
![image](https://user-images.githubusercontent.com/24497259/124548528-6e148f80-de60-11eb-9a8d-c07170e25d5d.png)
but when I clicked "Run", it didn't work
![image](https://user-images.githubusercontent.com/24497259/124548629-8f757b80-de60-11eb-9767-8084bbef2929.png)
after "Open in my browser", same warming.

**Comment by marcobertagna** [comment]
Hi, yesterday I tried again and it worked, the previous time it was as if it had "core version" errors and was unable to download packages.

**Comment by julien-moreau** [comment]
@marcobertagna fixed in latest templates of v4.1.0 ! :)
