### ISSUE TITLE
Additional Features/Roadmap for Plugin System

### ISSUE THREAD

**Issue by prestomation** [BabylonJS/Editor#336]
Hi,

I am interested in how we see the editor Plugin system evolving and if contributions are welcome here.

For example, today it does not appear that plugins can add additional asset types(`Assets.addAssetComponent(...)`) or graph node types (`LiteGraph.registerNodeType("mynodes/SpecialNode", MyNodeType);`)

Both of these seem like great extension points for the Editor, so that project/game teams can add their own asset types and visual scripting nodes to empower artists to accomplish more in the editor.

After doing some minimal step-through debugging/looking at the code, it looks like Assets simply doesn't know how to force a re-render. For LiteGraph, I'm guessing is a bit more complicated as the graph UI runs in another window, but I'm not very familiar with electron or how the multi-window setup works in the Babylon.js Editor.

In both cases, I suspect that the static nature of these systems can cause issues. Maybe the IPlugin interface can return IAssetComponent and IGraphNode, like it currently can inspectors? What do you think? Are there existing plans here? Do we think the plugin system should not be extended in this way?

**Comment by julien-moreau** [comment]
Hi @prestomation ! I'm back from holidays, sorry for the delay :)

You are right and all contributions are open of course! :)

Concerning the assets, I'm working on the version 4.1 where all assets management has been reworked to fit with the most common way: have a file explorer for assets instead of just "tabs". You can checkout this version preview using the branch `feature/workspace-assets`. This new assets component has been done to be hightly customizable and plugins can now register their own "asset preview" renderer with context menu support etc.

For the LiteGraph implementation, this is still in beta mode but it can already be customizable. The only things we must do are:
- add support of a better way to register nodes from a plugin
- add support for loading these custom nodes in the graph editor window (as you said and I agree, rendering graph editor in a separated window makes it more difficult)

If you want we can keep this issue opened and I can try to submit a first draft of how a plugin can register custom assets support and custom graph nodes support :)

**Comment by prestomation** [comment]
This sounds great! I'm happy to review/test and will find some time to look at the branch next week. Thank you!

**Comment by julien-moreau** [comment]
Hi @prestomation !

I have tried improving the plugins interface to easily include assets handlers, inspectors and graph nodes.

# Graph Editor
To register custom nodes, the plugin can now implement `registerGraphConfiguration `: https://github.com/BabylonJS/Editor/blob/feature/workspace-assets/sample-plugin/src/index.tsx#L18 so I'll be required by the graph editor window and the editor itself when generating the project

A custom node implementation is available here: https://github.com/BabylonJS/Editor/blob/feature/workspace-assets/sample-plugin/src/graph/basic-node.ts

# Inspectors
As well as the inspectors: https://github.com/BabylonJS/Editor/blob/feature/workspace-assets/sample-plugin/src/index.tsx#L45

An inspector example is available here: https://github.com/BabylonJS/Editor/blob/feature/workspace-assets/sample-plugin/src/inspectors/md-inspector.tsx

# Assets
Also for assets, the plugin can export item handlers (to render and add actions to items in the assets browser) this way: https://github.com/BabylonJS/Editor/blob/feature/workspace-assets/sample-plugin/src/index.tsx#L52 and move handler (called each time an asset is moved in the editor)

An asset item handler is available here: https://github.com/BabylonJS/Editor/blob/feature/workspace-assets/sample-plugin/src/assets/md-handler.tsx
In this example, when the user clicks on the asset, it notifies the editor's inspector

Don't hesitate if you have any suggestion / idea / feedback of course :)

**Comment by JuliaABurch** [comment]
Thank you so much for the work you've done here! Is there any kind of known timeline for the release of this feature branch?

**Comment by julien-moreau** [comment]
Hi @JuliaABurch !
I'm so sorry that I haven't seen your answer!

I just released the version 4.1.0 that includes these plugins improvements. Let me know if you have any feedback/feature request on the forum here: https://forum.babylonjs.com/ Other members may help using this forum :)
