### ISSUE TITLE
Scale factor and all those things

### ISSUE THREAD

**Issue by vortice3D** [BabylonJS/Editor#37]
Dear **Julien**:

A pair of questions that can be certainly related:

- it could be good to have some kind of **scale factor**, in order to be able to manage scenes with very-different scales from the default one of the editor;

- also, to have implemented the BJS Camera's **wheelPrecision** property would be great;

- by the way we find that the Camera's **speed** property doesn't work at all, or al least not as expected.

Best regards.

**Comment by julien-moreau** [comment]
I'm adding the wheel precision right now and the camera's properties options.

For the scale factor, as a designer you can add an empty node as the master parent node in your modeling tool, for the moment. Anyway, I'm adding the feature

**Comment by julien-moreau** [comment]
Fixed here! https://github.com/BabylonJS/Editor/commit/e31f116a012d82df43c13ec871dee83f1d44dda4

For the editor camera, I guess you would prefer to change the "panning sensibility" parameter instead of speed
The Scale Factor is available in the "Scene" tab on top of the tool (on the left)

<img width="1920" alt="capture d ecran 2017-11-30 a 21 20 23" src="https://user-images.githubusercontent.com/2620127/33453012-63a68a92-d614-11e7-80d5-5859ad2bcc4d.png">

Thanks for this feedback!!

**Comment by julien-moreau** [comment]
Also, the camera's configurations are saved when you save your project!

Let me know if I can close this issue :)

**Comment by julien-moreau** [comment]
Just fixed, that was a bug on my side, thanks for reporting this bug!

**Comment by vortice3D** [comment]
Ok **Julien**, thanks for your time:

Anyway, the case is that when you open/re-open a scene, the scale factor is reset to 1 again (so I think you doesn't serialize/save it within the file).

Also, environment is lost when you open a scene that you saved with that texture set (is not listed nor shown).

Best regards.
