### ISSUE TITLE
Unable to load from ./scenes/_assets/../scene/scene.babylon: loadAssets of scene.babylon from Babylon.JS

### ISSUE THREAD

**Issue by yxzyxzyxz** [BabylonJS/Editor#403]
When I run, the console reports an error.

```
Uncaught (in promise) RuntimeError: Unable to load from ./scenes/_assets/../scene/scene.babylon: loadAssets of scene.babylon from Babylon.JS Editor version: v4.4.0, exporter version: v5.19.0
	Lights:
		Name: sun, type: Directional
	Materials:
		Name: default material
		Name: cube
```

![image](https://user-images.githubusercontent.com/20411380/204416882-c5485b9e-65f2-46e5-84a0-23678d871883.png)

**Comment by julien-moreau** [comment]
Hey @yxzyxzyxz can you ensure you have added all the needed imports in your index.ts file ?
Babylon.JS uses ES6 modules and must import all the components you need. You can find more information here: https://doc.babylonjs.com/setup/frameworkPackages/es6Support

Also in order to get help from other users/developers I suggest that you use the forum: https://forum.babylonjs.com/
I'm closing this issue and if you failed to fix with the documentation I shared, feel free to open a new discussion on the forum

Thanks a lot !

**Comment by strowk** [comment]
I have this same issue. Could you please clarify what exactly the changes needed to be done in index.ts. To clarify, I haven't done anything in the project at all since creating it from "third person shooter" template. Maybe template contains the bug of some sort? 

I made also entry in forum - https://forum.babylonjs.com/t/unable-to-load-from-scenes-assets-scene-scene-babylon/38333/1

Please do not answer me with links to documentation, I'm pretty sure that template is supposed to work right away without additional actions

**Comment by strowk** [comment]
Also tried adding 
```

import {
    SkyMaterial
} from '@babylonjs/materials';

```

, as I think the documentation suggests to do, but this had no effect on the result unfortunately.
Template seems broken and it is not clear how to fix it.

**Comment by strowk** [comment]
Aha, so workarond is to remove the sky in Assets over here: 
<img width="724" alt="image" src="https://user-images.githubusercontent.com/25692644/219828080-1026b322-e9e8-4270-b9d4-d07e2831bd7c.png">

Why exactly this is broken like this is unclear at the moment, I think some of people, who understand more about this, should look into issue. Could you please reopen this bug?
