### ISSUE TITLE
Where are all the tools of v1?

### ISSUE THREAD

**Issue by julien-moreau** [BabylonJS/Editor#76]
where are all the tools of v1? (Behaviour Editor, Material Builder, Dynamic Texture Builder) if I understand some of them have been moved to View?

@Nodragem do you want to rename the menu from "Views" from "Tools"?

**Comment by Nodragem** [comment]
In fact, you also put the Texture Viewer and the Material Viewer there, right?

I think the right name would be "Windows" as it is named in Unity, because they are windows/panels that you add to your layout. Some are editors, some are viewers.

By the way, maybe you should rename "Textures..." and "Materials..." to "Texture Viewer" and "Material Viewer" in the menu to be clearer and match with the actual name of the related window.

**Comment by julien-moreau** [comment]
Done :)
